name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if ci/py${{ matrix.python-version }}.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/py${{ matrix.python-version }}.yml') }}
      - name: setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: pangeo-forge
          environment-file: ci/py${{ matrix.python-version }}.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: print conda env
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: install pangeo-forge
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/pangeo-forge/pangeo-forge
      - name: Lint recipes
        shell: bash -l {0}
        run: |
          for dir in recipes/*; do
            pangeo-forge check ${dir} --verbose
          done;
