name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  lint-black:
    name: black-formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Black
        run: |
          python -m pip install black
      - name: Black Code Formatter
        run: |
          black --check --line-length 100 --skip-string-normalization .

  lint-flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Flake8
        run: |
          python -m pip install flake8
      - name: Flake8 check
        run: |
          flake8 .

  lint-isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install isort
        run: |
          python -m pip install isort
      - name: isort check
        run: |
          isort --check-only .

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if ci/py${{ matrix.python-version }}.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('ci/py${{ matrix.python-version }}.yml') }}
      - name: setup miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: pangeo-forge
          environment-file: ci/py${{ matrix.python-version }}.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: print conda env
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: install pangeo-forge
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
      - name: Running Tests
        shell: bash -l {0}
        run: |
          python -m pytest --log-cli-level=WARNING --verbose
